#!/usr/bin/python

from mysql.connector import MySQLConnection, Error
from configparser import ConfigParser
from collections import defaultdict
from collections import Counter


#------------------------------------------------------------------------------
def read_db_config(filename='config.ini', section='mysql'):
   """ Read database configuration file and return a dictionary object
   :param filename: name of the configuration file
   :param section: section of database configuration
   :return: a dictionary of database parameters
   """
   # create parser and read ini configuration file
   parser = ConfigParser()
   parser.read(filename)

   # get section, default to mysql
   db = {}
   if parser.has_section(section):
      items = parser.items(section)
      for item in items:
         db[item[0]] = item[1]
   else:
      raise Exception('{0} not found in the {1} file'.format(section, filename))

   return db
#------------------------------------------------------------------------------
def getNetworks(conn):
   networks = {}
   try:
      cursor = conn.cursor()
      cursor.execute("""SELECT
    networks.id
    , networks.tenant_id
    , networks.name
    , networks.mtu
    , ml2_network_segments.network_type
    , ml2_network_segments.physical_network
    , ml2_network_segments.segmentation_id
FROM
    neutron.ml2_network_segments
    INNER JOIN neutron.networks 
        ON (ml2_network_segments.network_id = networks.id)""")
      rows = cursor.fetchall()
 
      
      for row in rows:
         rec = {}
         rec = { 
                  'id':  row[0], 
                  'name' : row[2],
                  'tenant_id' : row[1],
                  'mtu'   : row[3],
                  'network_type' : row[4],
                  'physical_network' : row[5],
                  'segmentation_id'  : row[6]
                  
               }
         networks[row[0]] = rec
      print "INFO: Total Networks(s):", cursor.rowcount
   except Error as e:
      print(e)
 
   finally:
      cursor.close()
      return(networks)
#------------------------------------------------------------------------------
def getSubnets(conn):
   subnets = {}
   try:
      cursor = conn.cursor()
      cursor.execute("SELECT id, tenant_id, name, network_id, ip_version, cidr, gateway_ip, enable_dhcp FROM subnets")
      rows = cursor.fetchall()
 
      
      for row in rows:
         rec = {}
         rec = { 
                  'id':  row[0], 
                  'tenant_id' : row[1],
                  'name'   : row[2],
                  'network_id' : row[3],
                  'ip_version' : row[4],
                  'cidr'   : row[5],
                  'gateway_ip'   : row[6],
                  'enable_dhcp'   : row[7]
               }
         subnets[row[0]] = rec
      print "INFO: Total Subnet(s):", cursor.rowcount
   except Error as e:
      print(e)
 
   finally:
      cursor.close()
      return(subnets)
  
      
#------------------------------------------------------------------------------    
def getDomains(conn):
   domains  = {}
   try:
      cursor = conn.cursor()
      cursor.execute("select id,name, description from keystone.project where is_domain = 1 and enabled = 1")
      rows = cursor.fetchall()
   
      
      for row in rows:
         rec = {}
         rec = { 
                  'id':  row[0], 
                  'name' : row[1],
                  'desc' : row[2]
               }
         domains[row[1]] = rec
      print "INFO: Total domain(s):", cursor.rowcount
   except Error as e:
      print(e)
 
   finally:
      cursor.close()
      return(domains)
#------------------------------------------------------------------------------    
def getProjects(conn):
   projects  = {}
   try:
      cursor = conn.cursor()
      cursor.execute("SELECT id,name, domain_id from keystone.project where is_domain = 0")
      rows = cursor.fetchall()
   
      
      for row in rows:
         rec = {}
         rec = { 
                  'id':  row[0], 
                  'name' : row[1],
                  'domain_id' : row[2]
                  
               }
         projects[row[0]] = rec
      print "INFO: Total projects(s):", cursor.rowcount
   except Error as e:
      print(e)
 
   finally:
      cursor.close()
      return(projects)
#------------------------------------------------------------------------------    
def getRouters(conn):
   routers  = {}
   try:
      dbconfig = read_db_config()
      #conn = MySQLConnection(**dbconfig)
      cursor = conn.cursor()
      cursor.execute("""SELECT
      routers.id
    , routers.tenant_id
    , routers.name
    , routers.status
    , routers.admin_state_up
    , routers.gw_port_id
    , routers.enable_snat
    , routerl3agentbindings.l3_agent_id
    , router_extra_attributes.distributed
    , router_extra_attributes.service_router
    , router_extra_attributes.ha
FROM
    neutron.routerl3agentbindings
    INNER JOIN neutron.routers 
        ON (routerl3agentbindings.router_id = routers.id)
    INNER JOIN neutron.agents 
        ON (routerl3agentbindings.l3_agent_id = agents.id)
    INNER JOIN neutron.router_extra_attributes 
        ON (router_extra_attributes.router_id = routers.id)""")
      rows = cursor.fetchall()
      #print "Rows = "
      #print rows
      
      for row in rows:
         rec = {}
         rec = { 
                  'uuid' : row[0], 
                  'tenant_id' : row[1], 
                  'name' : row[2],
                  'status' : row[3],
                  'enabled' : row[4],
                  'gw_port_id' : row[5],
                  'snat' : row[6],
                  'active_on' : row[7],
                  'distributed' : row[8],
                  'service_rtr' : row[9],
                  'isHA' : row[10]
               }
         #print "REC" + rec;      
         routers[row[0]] = rec
      #print "Total routers(s):", cursor.rowcount
   except Error as e:
      print(e)
 
   finally:
      print "INFO: Total routers(s):", cursor.rowcount
      cursor.close()
      #print "End of getRouters"
      return(routers)
#------------------------------------------------------------------------------

def generateSummary(my_routers, my_ports, my_projects, my_ipalloc, my_networks, my_subnets, my_agents , my_north_ports, my_south_ports ):
   #print "getting here"
   #print my_ports;
   #print my_routers;
   print "------------------------------------------------------------------------------"

   for k, v in my_routers.items():
   
      routerID = k
      #print "Generating summary for router : " + k
      name = v['name']
      snat = v['snat']
      router_tenant_id = v['tenant_id']
      # TO-DO: Throw an exception here
      if router_tenant_id in my_projects:
         router_tenant_name = my_projects[router_tenant_id]['name']
      else:
         router_tenant_name = 'None'
      
      if v['gw_port_id'] is None:
         print "Router " + name + " does not have a gateway defined. Skipping"
         continue
      
      gw_port_id = v['gw_port_id']
      
      #print "GatewayPortID = " + gw_port_id
      snat_value = "No"
      if snat == 1:
         snat_value = "Yes"
      # port details
      pd = my_ports[gw_port_id]
      #print my_ports;
      ipd = my_ipalloc[gw_port_id]
      
      network_id = ipd['network_id']; subnet_id = ipd['subnet_id'];
      #print ;
      #print network_id;
      north_side_config = pd['mac_address'] + ' / ' + ipd['ip_address'] + ' / ' + str(my_subnets[subnet_id]['cidr'])
      #+ ' / ' + subnet_cidr
      
      
      active_on_id = v['active_on']
      active_on_host = agents[active_on_id]['host']
      
      isDistributed = "No";
      if v['distributed'] ==1:
         isDistributed = "Yes"
      isHA = "No"   
      if v['isHA'] == 1:
         isHA = "Yes"
      
      # now handle the south ports
      south_port_id = my_south_ports[routerID]['port_id']
      south_port = my_ports[south_port_id]
      south_ip = my_ipalloc[south_port_id]
      south_network_id = south_ip['network_id']
      south_subnet_id = south_ip['subnet_id']
      #s_network_id = spd['network_id']; s_subnet_id = spd['subnet_id'];
      #south_side_config = spd['mac_address'] # + ' / ' + spIP['ip_address'] + ' / ' + str(my_subnets[s_subnet_id]['cidr'])
      south_side_config = south_port['mac_address'] + ' / ' + south_ip['ip_address']
      #print south_port
      header_format = '{:11} : {:50}'
      print header_format.format("Name", name)
      print header_format.format("Snat", snat_value)
      print header_format.format("UUID", v['uuid'])
      print header_format.format("Owner", router_tenant_name + ' [' + router_tenant_id + ']') 
      print header_format.format("Active On", active_on_host)
      print header_format.format("L3 Agent ID", active_on_id)
      print header_format.format("Distributed", isDistributed)
      print header_format.format("HA", isHA)
      
      print header_format.format("North Side", north_side_config)
      print header_format.format("", my_networks[network_id]['name'] + ' / ' + str(my_subnets[subnet_id]['cidr']))
      print header_format.format("", my_networks[network_id]['network_type'] + ' / ' + str(my_networks[network_id]['physical_network']) + ' / ' + str(my_networks[network_id]['segmentation_id']))
      
      print header_format.format("South Side", south_side_config)
      print header_format.format("", my_networks[south_network_id]['name'] + ' / ' + str(my_subnets[south_subnet_id]['cidr']))
      #print header_format.format("", my_networks[south_network_id]['network_type'] + ' / ' + my_networks[south_network_id]['physical_network'] + ' / ' + str(my_networks[south_network_id]['segmentation_id']))
      print header_format.format("", my_networks[south_network_id]['network_type'] + ' / ' + str(my_networks[south_network_id]['physical_network']) + ' / ' + str(my_networks[south_network_id]['segmentation_id']))
      
      
      print "------------------------------------------------------------------------------"
      
      
      
   # Let's figure out the number of infra nodes
   infraCtr = 0;
   infras = []
   for k, v in agents.items():

      agentID = k
   
      host = v['host'];
      topic = v['topic'];
      if topic == "l3_agent":
         a=host.split("-")
         infraCtr = infraCtr + 1
         #print "AgentID : " + agentID + " Host = " + a[0] + "-" + a[1] + " Topic = " + topic
         infras.append(a[0] + "-" + a[1])
   infras.sort()
   infraDisplay = "," . join(infras)
   print "There are " + str(infraCtr) + " infra node(s) : " + infraDisplay
      
      
      
      
      


def getPortDetails(ports, uuid):
   print ports[uuid];
   
   


#------------------------------------------------------------------------------    
def getRouterNorthPorts(conn):
   routerPorts  = {}
   try:
      cursor = conn.cursor()
      cursor.execute("SELECT router_id, port_id, port_type FROM neutron.routerports where port_type = 'network:router_gateway'")
      #cursor.execute("SELECT router_id, port_id, port_type FROM neutron.routerports")
      rows = cursor.fetchall()
   
      
      for row in rows:
         #print ">", row[0], "<" , ">", row[1] , "< >" , row[2] , "<"
         rec = {}
         rec = { 
                  'router_id':  row[0], 
                  'port_id' : row[1]
               }
         routerPorts[row[0]] = rec
      print "Total North ports(s):", cursor.rowcount
   except Error as e:
      print(e)
 
   finally:
      cursor.close()
      return(routerPorts)

#------------------------------------------------------------------------------    
def getComputeNodes(conn):
   computeNodes  = {}
   try:
      cursor = conn.cursor()
      cursor.execute("select id, host_ip, host from nova.compute_nodes")
      rows = cursor.fetchall()
   
      
      for row in rows:
         #print ">", row[0], "<" , ">", row[1] , "< >" , row[2] , "<"
         rec = {}
         rec = { 
                  'compute_id':  row[0], 
                  'host_ip' : row[1],
                  'hostname' : row[2]
               }
         computeNodes[row[0]] = rec
      print "Total Compute Nodes(s):", cursor.rowcount
   except Error as e:
      print(e)
 
   finally:
      cursor.close()
      return(computeNodes)


#------------------------------------------------------------------------------    
def getInstances(conn):
   instances  = {}
   try:
      cursor = conn.cursor()
      cursor.execute("select id, host, hostname, instance_type_id, vm_state, power_state from nova.instances where vm_state in ('active', 'stopped')")
      rows = cursor.fetchall()
   
      
      for row in rows:
         #print ">", row[0], "<" , ">", row[1] , "< >" , row[2] , "<"
         rec = {}
         rec = { 
                  'instance_id':  row[0], 
                  'host' : row[1],
                  'hostname' : row[2],
                  'vm_state' : row[3],
                  'power_state' : row[4]
               }
         instances[row[0]] = rec
      print "Total Instance(s):", cursor.rowcount
   except Error as e:
      print(e)
 
   finally:
      cursor.close()
      return(instances)
#------------------------------------------------------------------------------    
def getRouterSouthPorts(conn):
   routerPorts  = {}
   try:
      cursor = conn.cursor()
      cursor.execute("SELECT router_id, port_id, port_type FROM neutron.routerports where port_type = 'network:router_interface'")
      rows = cursor.fetchall()
   
      
      for row in rows:
         #print ">", row[0], "<" , ">", row[1] , "< >" , row[2] , "<"
         rec = {}
         rec = { 
                  'router_id':  row[0], 
                  'port_id' : row[1]
               }
         routerPorts[row[0]] = rec
      print "Total South ports(s):", cursor.rowcount
   except Error as e:
      print(e)
 
   finally:
      cursor.close()
      return(routerPorts)      

#------------------------------------------------------------------------------    
def getAgents(conn):
   agents  = {}
   try:
      cursor = conn.cursor()
      cursor.execute("SELECT id, agent_type, `binary`, topic, host, admin_state_up FROM neutron.agents")
      rows = cursor.fetchall()
   
      
      for row in rows:
         #print ">", row[0], "<" , ">", row[1] , "< >" , row[2] , "<"
         rec = {}
         rec = { 
                  'uuid':  row[0], 
                  'agent_type' : row[1], 
                  'binary' : row[2],
                  'topic' : row[3],
                  'host' : row[4],
                  'admin_state_up' : row[5]
               }
         agents[row[0]] = rec
      print "Total Neutron Agent(s):", cursor.rowcount
   except Error as e:
      print(e)
 
   finally:
      cursor.close()
      return(agents)
#------------------------------------------------------------------------------
      
   
   

#------------------------------------------------------------------------------    
def getPorts(conn):
   ports  = {}
   try:
      cursor = conn.cursor()
      cursor.execute("SELECT id, tenant_id, network_id,mac_address,admin_state_up, status, device_id, device_owner FROM neutron.ports")
      rows = cursor.fetchall()
   
      
      for row in rows:
         #print ">", row[0], "<" , ">", row[1] , "< >" , row[2] , "<"
         rec = {}
         rec = { 
                  'uuid':  row[0], 
                  'tenantid' : row[1], 
                  'network_id' : row[2],
                  'mac_address' : row[3],
                  'enabled' : row[4],
                  'status' : row[5],
                  'device_id'    : row[6],
                  'device_owner'    : row[7]
               }
         ports[row[0]] = rec
      print "Total ports(s):", cursor.rowcount
   except Error as e:
      print(e)
 
   finally:
      cursor.close()
      return(ports)
#------------------------------------------------------------------------------    
def getIPAllocations(conn):
   ipalloc  = {}
   try:
      cursor = conn.cursor()
      cursor.execute("SELECT port_id, ip_address, subnet_id, network_id FROM neutron.ipallocations")
      rows = cursor.fetchall()
      
      for row in rows:
         rec = {}
         rec = { 
                  'port_id':  row[0], 
                  'ip_address' : row[1], 
                  'subnet_id' : row[2],
                  'network_id' : row[3]
               }
         ipalloc[row[0]] = rec
      print "Total IP Allocation(s):", cursor.rowcount
   except Error as e:
      print(e)
 
   finally:
      cursor.close()
      return(ipalloc)      
#------------------------------------------------------------------------------
def connect():
   """ Connect to MySQL database """

   db_config = read_db_config()

   try:
      print('Connecting to MySQL database...')
      conn = MySQLConnection(**db_config)

      if conn.is_connected():
         print('connection established.')
      else:
         print('connection failed.')

   except Error as error:
      print(error)

   finally:
      return conn   
      #print('Connection closed.')
   
#------------------------------------------------------------------------------    
def disconnect(conn):
   conn.close();
   print("MySQL Connection Closed");
#------------------------------------------------------------------------------

      
if __name__ == '__main__':
   dbc = connect()      
   
   print "Collecting Information.."
   networks = getNetworks(dbc)
   agents = getAgents(dbc)
   routers  = getRouters(dbc)
   projects = getProjects(dbc)
   ports = getPorts(dbc)
   routerNorthPorts = getRouterNorthPorts(dbc)
   routerSouthPorts = getRouterSouthPorts(dbc)
   domains = getDomains(dbc)
   ipalloc = getIPAllocations(dbc)
   subnets = getSubnets(dbc)
   computes = getComputeNodes(dbc)
   instances = getInstances(dbc)
   disconnect(dbc)
   
   # now generate summary
   generateSummary(routers, ports, projects, ipalloc, networks, subnets, agents, routerNorthPorts, routerSouthPorts)
